version: "3"
volumes:
  js-volume:
    labels:
      description: "built js goes here"
services:
  db:
    build: db
    env_file:
      - db.env
  sql:
    build: sql
    env_file:
      - db.env
    depends_on:
      - db
  api:
    build: api
    depends_on:
      - db
  ui:
    build: ui
    command: [npm, run, watch]
    volumes:
      - js-volume:/node/public
      - ./ui/src:/node/src
  web:
    build: web
    volumes:
      - js-volume:/usr/share/nginx/js
      - ./web/public:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
