#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $API_USER PASSWORD '$API_PASS';
  CREATE DATABASE $API_DB;
  GRANT ALL PRIVILEGES ON DATABASE $API_DB TO $API_USER;
EOSQL
